project:
  type: website
  
website:
  title: "Mikkel H. Vembye"
  site-url: https://mbye.com
  repo-url: https://github.com/MikkelVembye/mbye-quarto
  description: "Systematic Reviewing and Meta-Analysis"
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: CV
        href: /files/Vembye-CV.pdf
      - text: Working Papers
        href: working-papers/index.qmd
      - text: Publications
        href: publications/index.qmd
      - href: presentations/index.qmd
      - href: software/index.qmd
      - contact.qmd
      
  page-footer: 
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) <br>
      [{{< fa brands github >}} Source](https://github.com/MikkelVembye/mbye-quarto)
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    linkcolor: "#3f51b5"
    fontcolor: "#313131"
    smooth-scroll: true